---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease

metadata:
  name: github-demo-fe
  namespace: github-demo
  annotations:
    flux.weave.works/automated: "true"
    filter.fluxcd.io/chart-image: glob:main-*

spec:
  wait: true
  timeout: 600
  resetValues: true
  forceUpgrade: true
  chart:
    git: git@github.com:spring-media/github-demo.git
    path: chart/github-demo
    ref: main

  values:
    image: ghcr.io/spring-media/github-demo/universe-2020-demo:main-3a0f41f

    url:
    - github-demo.test.mediasites.springtools.de
    - github-demo.books-1.test.euw1.mediasites.springtools.de
    - github-demo.books-2.test.euw1.mediasites.springtools.de
