apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: github-pull-secret
  namespace: github-demo-feature-xxx-111
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: github_docker_registry_config_json
      name: .dockerconfigjson
